class Answer:
    def __init__(self, text: str, isCorrect: bool, id: int = None):
        self.id = id  # Optional: ID of the answer (used when fetching from the database)
        self.text = text
        self.isCorrect = isCorrect
    def __repr__(self):
        return f"Answer(id={self.id}, text={self.text}, isCorrect={self.isCorrect})"

class Question:
    def __init__(self, position: int, title: str, text: str, image: str = None, possibleAnswers:list = None,id: int = None):
        self.id = id
        self.position = position
        self.title = title
        self.text = text
        self.image = image
        self.possibleAnswers = possibleAnswers or []
     
    def __repr__(self):
        return (
            f"Question(id={self.id}, position={self.position}, title={self.title}, "
            f"text={self.text}, image={self.image}, "
            f"possibleAnswers={self.possibleAnswers})"
        )

from typing import List, Optional

class Participation:
    def __init__(self, playerName: str, answers: List[int], score: int, id: Optional[int] = None):
        """
        Represents a participation record.
        :param id: Unique identifier for the participation (optional, auto-generated by the database).
        :param playerName: Name of the participant.
        :param answers: List of answers provided by the participant.
        :param score: Score achieved by the participant.
        """
        self.id = id
        self.playerName = playerName
        self.answers = answers
        self.score = score

    def __repr__(self):
        return f"Participation(id={self.id}, playerName={self.playerName}, answers={self.answers})"